name: ecommerce
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

#-----------------Packages--------------#

dependencies:
  flutter:
    sdk: flutter




  #UTILITY PACKAGES
 # icons
  iconsax:  ^0.0.8
  cupertino_icons: ^1.0.8
  carousel_slider: ^4.2.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  # state management
  get: ^4.6.6
  get_storage: ^2.1.1
  #utility packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.3.0
  lottie: ^3.1.2
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  #firebase
  firebase_core: ^3.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0





flutter:

  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/onboarding_images/
    - assets/images/signup_images/
    - assets/vegeicons/
    - assets/images/banners/

  #---------Local fonts--------------------------#
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 300
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 400
        - asset:  assets/fonts/Poppins-BlackItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
