// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFUPaxBa7HeNsrRtf7H8yDdkpPxBYhAXM',
    appId: '1:357441208677:web:0e4198c790df0caf10618c',
    messagingSenderId: '357441208677',
    projectId: 'grocery-app-e1646',
    authDomain: 'grocery-app-e1646.firebaseapp.com',
    storageBucket: 'grocery-app-e1646.appspot.com',
    measurementId: 'G-LPCRKQ2N55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsivbItnSMQTJtddDy39LHRUAfMdRAVHs',
    appId: '1:357441208677:android:2ae4caa771c9386310618c',
    messagingSenderId: '357441208677',
    projectId: 'grocery-app-e1646',
    storageBucket: 'grocery-app-e1646.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeaIji3_n_ugbvrD-gTXIY1TdCgLjqcaU',
    appId: '1:357441208677:ios:b357e845735ea17810618c',
    messagingSenderId: '357441208677',
    projectId: 'grocery-app-e1646',
    storageBucket: 'grocery-app-e1646.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFUPaxBa7HeNsrRtf7H8yDdkpPxBYhAXM',
    appId: '1:357441208677:web:f70e595e7158250710618c',
    messagingSenderId: '357441208677',
    projectId: 'grocery-app-e1646',
    authDomain: 'grocery-app-e1646.firebaseapp.com',
    storageBucket: 'grocery-app-e1646.appspot.com',
    measurementId: 'G-XYBK03GHKH',
  );
}
